<!DOCTYPE html><html lang="en"><head><?php $profil=$profil->row_array(); $nama_app=$profil['nama_app']; ?> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <meta name="description" content=""> <meta name="author" content=""> <title><?php echo $nama_app; ?></title> <link href="<?php echo base_url('assets/fontawesome-free/css/all.min.css') ?>" rel="stylesheet" type="text/css"> <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet"> <link href="<?php echo base_url('css/sb-admin-2.css') ?>" rel="stylesheet"> <link rel="shortcut icon" type="image/x-icon" href="<?php echo base_url('img/logokotamedan.png')?>"/>
</head>
<body class="bg-gradient-primary"> 
<div class="container"> 
<div class="row justify-content-center"> 
<div class="col-xl-6 col-lg-6 col-md-9"> 
<div class="card o-hidden border-0 shadow-lg my-5"> 
<div class="card-body p-0"> 
<div class="row"> 
<!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->
<div class="col-lg-12"> 
<div class="p-5"> 
<div class="text-center"> 
<!-- <img src="<?php echo base_url('img/logokotamedan.png')?>"> -->
<h1 class="h5 text-gray-900 mb-4"><?php echo "Login<br> APP ".$nama_app; ?></h1> </div><?php //if(isset($error)){echo $error;}; if($this->session->flashdata('notif')){echo $this->session->flashdata('notif');}?> <form method="post" id="login" autocomplete="on"> <div class="form-group"> <input type="email" name="username" class="form-control form-control-user" id="text_username" aria-describedby="emailHelp" placeholder="Input Email Anda "> </div><?php echo form_error('username'); ?> <div class="form-group"> <input type="password" name="password" class="form-control form-control-user" id="text_password" placeholder="Input Password Anda"> </div><?php echo form_error('password'); ?> <div class="form-group row"> <div class="col-sm-6 mb-3 mb-sm-0"> <?php echo $captcha_image ?> <a href="#" onclick="parent.window.location.reload(true)"><img src="<?php echo base_url('img/refresh.png') ?>" width="16%"> </a> </div><div class="col-sm-6"> <input type="text" name="input_captcha" class="form-control form-control-user" placeholder="Masukkan Captcha"> </div></div><?php echo form_error('input_captcha'); ?> <script src="<?php echo base_url('js/jquery.min.js') ?>"></script> <div class="form-group"> <div class="custom-control custom-checkbox small"> <input type="checkbox" class="custom-control-input" id="customCheck"> <label class="custom-control-label" for="customCheck">Ingatkan saya</label> </div></div><button class="btn btn-primary btn-user btn-block" name="btn-login" id="btn-login" type="submit">Masuk</button> <div class="load"></div>

<br>
 Belum Punya akun ? Silahkan <a href="<?php echo base_url('Web/register'); ?>"> MENDAFTAR</a>
 <!-- <hr> <a href="index.html" class="btn btn-google btn-user btn-block"> <i class="fab fa-google fa-fw"></i> Login with Google </a> <a href="index.html" class="btn btn-facebook btn-user btn-block"> <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook </a> --> </form> <hr> <div class="row"> <?php echo "<div class='col-sm-12 mb-3 mb-sm-0 text-left small'>" .$nama_app." 29 Desember 2020 - Dev. Edison TP. DOloksaribu, S.SI</div>"; ?><!-- <div class="col-sm-6 mb-3 mb-sm-0 text-left"> <a class="small" href="#">Forgot Password?</a> </div><div class="col-sm-6 mb-3 mb-sm-0 text-right"> <a class="small" href="#">Create an Account!</a> </div>--> </div></div></div></div></div></div></div></div></div><script src="<?php echo base_url('assets/jquery/jquery.min.js') ?>"></script> <script src="<?php echo base_url('assets/bootstrap/js/bootstrap.bundle.min.js') ?>"></script> <script src="<?php echo base_url('assets/jquery-easing/jquery.easing.min.js') ?>"></script> <script src="<?php echo base_url('js/sb-admin-2.min.js') ?>"></script> <script src="<?php echo base_url('js/sweetalert.min.js') ?>"></script> <script type="text/javascript">//Minify dengan https://javascript-minifier.com/  
  $(document).ready(function(){$("#login").on("submit",function(a){$.ajax({url:"<?php echo base_url() ?>/login",type:"POST",dataType:"json",data:$(this).serialize(),beforeSend:function(){$("#btn-login").hide(),$(".load").addClass("loading")},success:function(a){"success"==a.status?(swal({type:"success",title:"Login Sukses",icon:"success",showConfirmButton:!0,timer:1500}),window.setTimeout(function(){window.location.replace("")},1500)):"gagalcaptcha"==a.status?(swal("GAGAL CAPTCHA","Login Gagal Captcha SALAH Segarkan browser anda:(","error"),$("#btn-login").show(),$(".load").hide()):(swal("GAGAL USER LOG","Login Gagal Username atau Password SALAH:(","error"),$("#btn-login").show(),$(".load").hide())},error:function(a){swal("Oops...","Terjadi kesalahan, Semua Form harus diisi :(","error"),$("#btn-login").show(),$(".load").hide()}}),a.preventDefault()})});
  </script></body></html>